include:
  # Sofle v2.0w
  - board: nice_nano_v2
    shield: sofle_left nice_view_adapter nice_view_gem
  - board: nice_nano_v2
    shield: sofle_right nice_view_adapter nice_view_gem
    # For use as a dongle with the Prospector adapter
  - board: seeeduino_xiao_ble
    shield: sofle_dongle rgbled_adapter nice_view_adapter prospector_adapter
    cmake-args: -DCONFIG_ZMK_STUDIO=n

  # Toucan
  - board: seeeduino_xiao_ble
    shield: toucan_left rgbled_adapter nice_view_gem_toucan
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: seeeduino_xiao_ble
    shield: toucan_right rgbled_adapter

  # Prospector Scanner
  - board: seeeduino_xiao_ble
    shield: prospector_scanner

  # Settings reset
  - board: nice_nano_v2
    shield: settings_reset
  - board: seeeduino_xiao_ble
    shield: settings_reset